### ISSUE TITLE
Math Domain Error

### ISSUE THREAD

**Issue by SPPearce** [jin-wash-u/HPV-EM#8]
Hi,

I'm trying to run your code and getting the following error:

```
Running EM algorithm
Traceback (most recent call last):
  File "HPV-EM.py", line 213, in <module>
    main()
  File "HPV-EM.py", line 207, in main
    EmAlgo(readsTable, allReadsNum, thresholdTpm=args.tpm, outputName=args.outname, printResult=args.printem)
  File "HPV-EM/EMstep.py", line 120, in EmAlgo
    l +=  w[i,j] * math.log(((1.-err)**Lm * err**Le * phi[j])/w[i,j])
ValueError: math domain error
```

Any suggestions on how to fix this?

**Comment by kristianunger** [comment]
I get the same error "line 120, in EmAlgo  l +=  w[i,j] * math.log(((1.-err)**Lm * err**Le * phi[j])/w[i,j])" 
@jin-wash-u do you have any directions how this could be solved? I am running the algorithm on single-end 3'-Seq RNAseq data. Alignment and plots are fine until the error.
